# **ESERCIZI LEZIONE 1**

## ***ESERCIZIO 1***

### *ESEMPIO 1*

In [8]:
lista1=[]
for i in range(10):
    lista1.append(i)
print(lista1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1]:
lista1=[i for i in range(10)]
print(lista1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### *ESEMPIO 2*

In [2]:
lista2=[]
for letter in "contemporaneamente":
    lista2.append(letter)
print(lista2)

['c', 'o', 'n', 't', 'e', 'm', 'p', 'o', 'r', 'a', 'n', 'e', 'a', 'm', 'e', 'n', 't', 'e']


In [3]:
lista2=[letter for letter in "contemporaneamente"]
print(lista2)

['c', 'o', 'n', 't', 'e', 'm', 'p', 'o', 'r', 'a', 'n', 'e', 'a', 'm', 'e', 'n', 't', 'e']


### *ESEMPIO 3*

In [4]:
lista3=[]
for number in range(2,11):
    lista3.append(number**2)
print(lista3)

[4, 9, 16, 25, 36, 49, 64, 81, 100]


In [5]:
lista3=[number**2 for number in range(2,11)]
print(lista3)

[4, 9, 16, 25, 36, 49, 64, 81, 100]


## ***ESERCIZIO 2***

In [6]:
import numpy as np

arr = np.array([2,3,5,7])
print(len(arr))
print(arr.size)

print(arr.dtype)

def primo(numero):
    if numero<2:
        return None
    for i in range(2,int(numero**0.5)+1):
        if numero%i == 0:
            return None
    return numero

array = [i for i in [2,3,4,5,6,7,8,9,10] if primo(i) is not None]
print(array)


4
4
int64
[2, 3, 5, 7]


## ***ESERCIZIO 3***

In [ ]:
import numpy as np

a = np.arange(1,6)
b = a[1:4]
c = a[::-1]
division = a/c
print(a)
print(b)
print(c)
print(division)

lista = list(a)
listab=lista[1:4]
listac=lista[::-1]
division_lista= np.array(lista)/np.array(listac)
print(division_lista)

[1 2 3 4 5]
[2 3 4]
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
[0.2 0.5 1.  2.  5. ]
[0.2, 0.5, 1.0, 2.0, 5.0]
