# **ESERCIZI LEZIONE 1**

## ***ESERCIZIO 1***

### *ESEMPIO 1*

In [2]:
lista = []
for number in range(1,10):
    lista.append(number*2)
print(lista)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [3]:
lista = [number*2 for number in range(1,10)]
lista

[2, 4, 6, 8, 10, 12, 14, 16, 18]

### *ESEMPIO 2*

In [ ]:
lista_nomi = []
names = ["andrea", "marco", "anna", "giovanni","angelo"]
for name in names:
    lista_nomi.append(name)
lista_nomi

['andrea', 'marco', 'anna', 'giovanni']

In [5]:
names = ["andrea", "marco", "anna", "giovanni", "angelo"]
lista_nomi = [name for name in names]
lista_nomi

['andrea', 'marco', 'anna', 'giovanni', 'angelo']

### *ESEMPIO 3*

In [6]:
lista = []
for lettera in "contemporaneamente":
    lista.append(lettera)
lista

['c',
 'o',
 'n',
 't',
 'e',
 'm',
 'p',
 'o',
 'r',
 'a',
 'n',
 'e',
 'a',
 'm',
 'e',
 'n',
 't',
 'e']

In [7]:
lista = [lettera for lettera in "contemporaneamente"]
lista

['c',
 'o',
 'n',
 't',
 'e',
 'm',
 'p',
 'o',
 'r',
 'a',
 'n',
 'e',
 'a',
 'm',
 'e',
 'n',
 't',
 'e']

## ***ESERCIZIO 2***

In [8]:
import numpy as np

arr = np.array([2,3,5,7])
print(len(arr))
print(arr.size)

print(arr.dtype)

def primo(numero):
    if numero<2:
        return None
    for i in range(2,int(numero**0.5)+1):
        if numero%i == 0:
            return None
    return numero

array = [i for i in range(0,10) if primo(i) is not None]
print(array)


4
4
int64
[2, 3, 5, 7]


## ***ESERCIZIO 3***

In [9]:
import numpy as np

a = np.arange(1,6)
b = a[1:4]
c = a[::-1]
division = a/c
print(a)
print(b)
print(c)
print(division)

lista = list(a)
listab=lista[1:4]
listac=lista[::-1]
division_lista= np.array(lista)/np.array(listac)
print(division_lista)
print(division_lista.tolist())

[1 2 3 4 5]
[2 3 4]
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
[0.2 0.5 1.  2.  5. ]
[0.2, 0.5, 1.0, 2.0, 5.0]
