# **ESERCIZI LEZIONE 2**

### ***1. INDICIZZAZIONE BOOLEANA***

In [72]:
import numpy as np

v = np.array([2,3,5,7,11,13,17,19])

v[v>10]

v[v%2==0]


array([2])

### ***2. OPERAZIONI SU ARRAY***

In [73]:
import numpy as np

a = np.random.randint(1,10,(4,4))
print(a)

b = a[[1,3],:]
print(b)

c = a[2,:]
print(c)

result = a/c
print(result)


[[9 4 2 4]
 [7 6 1 1]
 [4 5 4 2]
 [4 7 9 1]]
[[7 6 1 1]
 [4 7 9 1]]
[4 5 4 2]
[[2.25 0.8  0.5  2.  ]
 [1.75 1.2  0.25 0.5 ]
 [1.   1.   1.   1.  ]
 [1.   1.4  2.25 0.5 ]]


### ***3. SELEZIONA IL NUMERO PIU' VICINO A 0.5 IN UN ARRAY CASUALE***

In [74]:
import numpy as np

a = np.random.rand(10, 3)
print("Array a:\n", a)

distanze = np.abs(a - 0.5)

indici_minimi = np.argmin(distanze, axis=1)

valori_selezionati = a[np.arange(a.shape[0]), indici_minimi]

print("\nValori più vicini a 0.5 per ogni riga:\n", valori_selezionati)


Array a:
 [[0.26013496 0.03489386 0.64875097]
 [0.66120876 0.79088234 0.39501653]
 [0.94186985 0.64812987 0.88404938]
 [0.16921869 0.35410287 0.32309142]
 [0.28355512 0.2057366  0.86833568]
 [0.24116189 0.11477416 0.71477893]
 [0.67880596 0.00612642 0.57106539]
 [0.08398088 0.57167806 0.40614326]
 [0.81144784 0.45840582 0.36543366]
 [0.80047934 0.65350094 0.6295436 ]]

Valori più vicini a 0.5 per ogni riga:
 [0.64875097 0.39501653 0.64812987 0.35410287 0.28355512 0.71477893
 0.57106539 0.57167806 0.45840582 0.6295436 ]


### ***4. ANALISI DELLA FREQUENZA CARDIACA CON NUMPY***

In [75]:
import numpy as np

frequenze = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

frequenza_min = np.min(frequenze)

frequenza_max = np.max(frequenze)

sforzo = frequenze>120

percentuale = np.mean(sforzo)*100

print(percentuale)

52.38095238095239


### ***5. MAIPOLAZIONE DI VETTORI***

In [76]:
import numpy as np

stipendi = np.array([50000,105250,55000,89000])

costo = np.sum(stipendi)

stipendi[1] *= 1.15
print(stipendi)

stipendi2 = np.array([50000,105250,55000,89000], dtype=np.float64)

stipendi2[1] *= 1.15
print(stipendi2)

stipendi2[0] *= 1.2

stipendi2[[2, 3]] *= 1.1

costo_finale = np.sum(stipendi2)

differenza = costo_finale-costo

print(differenza)



[ 50000 121037  55000  89000]
[ 50000.  121037.5  55000.   89000. ]
40187.5
